from django.urls import path
from .views import login_view
from .views import (
    UserListCreateView,
    UserRetrieveUpdateDestroyView,
    TopicListCreateView,
    PostListCreateView,
    PostRetrieveUpdateDestroyView,
    LikeListCreateView,
    LikeRetrieveUpdateDestroyView,
    CommentListCreateView,
    CommentRetrieveUpdateDestroyView,
    ChatListCreateView,
    ChatRetrieveUpdateDestroyView,
    MessageListCreateView,
    MessageRetrieveUpdateDestroyView,
    SubscribeToTopicView,
    subscribed_feed,
    FollowingListAPIView,
    UserTopicsListAPIView,
    UserPostsListAPIView,
    FollowUserView,
    UnfollowUserView,
    IsFollowingUserView,
    UserFollowersListAPIView,
    UserFollowingListAPIView,
    get_user_topics,
    unsubscribe_topic
)

urlpatterns = [
    path('users/', UserListCreateView.as_view(), name='user-list-create'),
    path('users/<int:pk>/', UserRetrieveUpdateDestroyView.as_view(), name='user-retrieve-update-destroy'),
    path('topics/', TopicListCreateView.as_view(), name='topic-list-create'),
    path('posts/', PostListCreateView.as_view(), name='post-list-create'),
    path('posts/<int:pk>/', PostRetrieveUpdateDestroyView.as_view(), name='post-retrieve-update-destroy'),
    path('likes/', LikeListCreateView.as_view(), name='like-list-create'),
    path('likes/<int:pk>/', LikeRetrieveUpdateDestroyView.as_view(), name='like-retrieve-update-destroy'),
    path('comments/', CommentListCreateView.as_view(), name='comment-list-create'),
    path('comments/<int:pk>/', CommentRetrieveUpdateDestroyView.as_view(), name='comment-retrieve-update-destroy'),
    path('chats/', ChatListCreateView.as_view(), name='chat-list-create'),
    path('chats/<int:pk>/', ChatRetrieveUpdateDestroyView.as_view(), name='chat-retrieve-update-destroy'),
    path('messages/', MessageListCreateView.as_view(), name='message-list-create'),
    path('messages/<int:pk>/', MessageRetrieveUpdateDestroyView.as_view(), name='message-retrieve-update-destroy'),
    path("auth/login/", login_view, name="login"),
    path("subscribe/", SubscribeToTopicView.as_view(), name="subscribe"),
    path('subscribed_feed/', subscribed_feed, name='subscribed_feed'),
    path('following/', FollowingListAPIView.as_view(), name='following-list'),
    path('topics/', UserTopicsListAPIView.as_view(), name='user-topics-list'),
    path('users/<int:pk>/posts/', UserPostsListAPIView.as_view(), name='user-posts-list'),
    path('users/<int:pk>/follow/', FollowUserView.as_view(), name='follow-user'),
    path('users/<int:pk>/unfollow/', UnfollowUserView.as_view(), name='unfollow-user'),
    path('users/<int:pk>/is_following/', IsFollowingUserView.as_view(), name='is-following-user'),
    path('users/<int:pk>/followers/', UserFollowersListAPIView.as_view(), name='user-followers-list'),
    path('users/<int:pk>/following/', UserFollowingListAPIView.as_view(), name='user-following-list'),
    path('users/<int:user_id>/topics/', get_user_topics, name='get_user_topics'),
    path('users/<int:user_id>/topics/<int:topic_id>/unsubscribe/', unsubscribe_topic, name='unsubscribe_topic'),
]
