# Generated by Django 4.2 on 2023-05-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_alter_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
